import { StyleSheet } from "@react-pdf/renderer";

export const pdfColors = {
  white: "#FFFFFF",
  black: "#000000",
  dark: "#1a1a1a",
  ctaYellow: "#E7C51C",
  sand100: "#FAF9F8",
  sand300: "#E6E5E0",
  sand500: "#D0D6D0",
  grey400: "#6B6B68",
  grey500: "#424242",
  grey600: "#2E2E2E",
};

const PDF_RADIUS_SMALL = 4;
const PDF_RADIUS_CARD = 8;

export const pdfStyles = StyleSheet.create({
  page: {
    backgroundColor: pdfColors.white,
    paddingBottom: 30,
    paddingTop: 70,
    fontFamily: "Helvetica",
  },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: pdfColors.black,
    paddingHorizontal: 40,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  logoWrap: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerLogo: {
    width: 112,
    height: 24,
    objectFit: "contain",
  },
  logoMark: {
    width: 18,
    height: 18,
    borderRadius: 3,
    backgroundColor: pdfColors.ctaYellow,
    color: pdfColors.black,
    fontSize: 12,
    fontWeight: 800,
    textAlign: "center",
    lineHeight: 1.5,
    marginRight: 6,
  },
  logoText: {
    color: pdfColors.white,
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 1,
  },
  headerDate: {
    color: pdfColors.grey400,
    fontSize: 9,
    fontWeight: 500,
  },
  content: {
    paddingHorizontal: 40,
    paddingTop: 0,
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: pdfColors.sand300,
    paddingHorizontal: 40,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  footerText: {
    fontSize: 8,
    color: pdfColors.grey400,
  },
  footerPage: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: pdfColors.black,
    color: pdfColors.white,
    textAlign: "center",
    fontSize: 8,
    paddingTop: 3,
    fontWeight: 700,
  },
  titleSection: {
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.sand500,
    paddingTop: 8,
    paddingBottom: 12,
    marginBottom: 12,
  },
  docTitle: {
    fontSize: 30,
    fontWeight: 700,
    color: pdfColors.black,
    marginBottom: 8,
  },
  badgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  badge: {
    backgroundColor: pdfColors.sand300,
    color: pdfColors.grey500,
    fontSize: 8,
    fontWeight: 600,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: PDF_RADIUS_SMALL,
    marginHorizontal: 2,
    marginBottom: 4,
  },
  badgeHighlight: {
    backgroundColor: pdfColors.ctaYellow,
    color: pdfColors.black,
  },
  sectionHeading: {
    fontSize: 12,
    fontWeight: 700,
    color: pdfColors.black,
    marginTop: 0,
    marginBottom: 8,
  },
  statsBar: {
    flexDirection: "row",
    backgroundColor: pdfColors.black,
    borderRadius: PDF_RADIUS_CARD,
    paddingVertical: 10,
    marginBottom: 10,
  },
  statItem: {
    flex: 1,
    alignItems: "center",
  },
  statValue: {
    fontSize: 16,
    fontWeight: 700,
    color: pdfColors.ctaYellow,
  },
  statLabel: {
    marginTop: 2,
    fontSize: 7,
    color: pdfColors.grey400,
    textTransform: "uppercase",
  },
  menuGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -4,
    marginBottom: 10,
  },
  menuCard: {
    width: "33.33%",
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  menuCardInner: {
    backgroundColor: pdfColors.sand100,
    borderWidth: 1,
    borderColor: pdfColors.sand300,
    borderRadius: PDF_RADIUS_CARD,
    padding: 6,
    minHeight: 52,
  },
  menuDay: {
    fontSize: 7,
    color: pdfColors.grey400,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  menuTitle: {
    fontSize: 8,
    color: pdfColors.black,
    fontWeight: 600,
    lineHeight: 1.3,
  },
  recipeCard: {
    borderWidth: 1,
    borderColor: pdfColors.sand300,
    backgroundColor: pdfColors.sand100,
    borderRadius: PDF_RADIUS_CARD,
    overflow: "hidden",
    marginBottom: 10,
  },
  recipeHeader: {
    backgroundColor: pdfColors.black,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  dayBadge: {
    backgroundColor: pdfColors.ctaYellow,
    color: pdfColors.black,
    fontSize: 8,
    fontWeight: 700,
    borderRadius: PDF_RADIUS_SMALL,
    paddingVertical: 3,
    paddingHorizontal: 6,
    marginRight: 8,
  },
  recipeTitle: {
    fontSize: 11,
    color: pdfColors.ctaYellow,
    fontWeight: 700,
    flex: 1,
    textDecoration: "none",
  },
  recipeBody: {
    padding: 10,
  },
  metaRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.sand300,
    paddingBottom: 6,
    marginBottom: 6,
    alignItems: "center",
  },
  metaThumbnailWrap: {
    width: 45,
    marginRight: 8,
  },
  metaItemsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    flex: 1,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 12,
    marginBottom: 4,
  },
  recipeThumbnail: {
    width: 45,
    height: 45,
    borderRadius: 4,
    objectFit: "cover",
  },
  metaText: {
    fontSize: 8,
    color: pdfColors.grey400,
    marginLeft: 3,
  },
  metaStrong: {
    color: pdfColors.black,
    fontWeight: 700,
  },
  recipeColumns: {
    flexDirection: "row",
  },
  ingredientsCol: {
    width: "40%",
    paddingRight: 8,
  },
  methodCol: {
    width: "60%",
    paddingLeft: 4,
  },
  colHeading: {
    fontSize: 8,
    fontWeight: 700,
    color: pdfColors.black,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  ingredientRow: {
    flexDirection: "row",
    marginBottom: 2,
  },
  ingredientBullet: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginTop: 4,
    marginRight: 4,
    backgroundColor: pdfColors.grey400,
  },
  ingredientText: {
    flex: 1,
    fontSize: 8,
    color: pdfColors.grey600,
    lineHeight: 1.35,
  },
  stepRow: {
    flexDirection: "row",
    marginBottom: 3,
  },
  stepNumber: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: pdfColors.sand300,
    color: pdfColors.grey500,
    fontSize: 7,
    fontWeight: 700,
    textAlign: "center",
    marginRight: 5,
    paddingTop: 2,
  },
  stepText: {
    flex: 1,
    fontSize: 8,
    color: pdfColors.grey600,
    lineHeight: 1.4,
  },
  shoppingGrid: {
    flexDirection: "column",
    marginBottom: 6,
  },
  shoppingCategory: {
    width: "100%",
    marginBottom: 6,
  },
  shoppingCategoryInner: {
    borderWidth: 1,
    borderColor: pdfColors.sand300,
    borderRadius: PDF_RADIUS_CARD,
    backgroundColor: pdfColors.sand100,
    padding: 6,
  },
  shoppingHeader: {
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.sand300,
    paddingBottom: 3,
    marginBottom: 4,
  },
  shoppingTitle: {
    fontSize: 8.5,
    color: pdfColors.black,
    fontWeight: 700,
  },
  shoppingItemRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 2,
  },
  checkbox: {
    width: 6,
    height: 6,
    borderWidth: 1,
    borderColor: pdfColors.grey400,
    borderRadius: 1,
    marginRight: 4,
    marginTop: 1.5,
  },
  shoppingText: {
    flex: 1,
    fontSize: 7.5,
    color: pdfColors.grey600,
    lineHeight: 1.3,
  },
  tipsBox: {
    borderLeftWidth: 3,
    borderLeftColor: "#C7CC87",
    backgroundColor: pdfColors.sand100,
    borderWidth: 1,
    borderColor: pdfColors.sand300,
    borderRadius: PDF_RADIUS_CARD,
    padding: 6,
    marginTop: 6,
  },
  tipsTitle: {
    fontSize: 9,
    fontWeight: 700,
    color: pdfColors.black,
    marginBottom: 4,
  },
  tipText: {
    fontSize: 8,
    color: pdfColors.grey400,
    lineHeight: 1.45,
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 9,
    color: pdfColors.grey400,
    marginBottom: 8,
  },
});
