import { Recommendation, TaskMatchResponse } from "./types";

export const mockRecommendations: Recommendation[] = [
  {
    _key: "mock-001",
    name: "Croco Embossed Day Chic Day Coat",
    brand: "Nour Hammour",
    description: "Statement leather outerwear that elevates simple layers with a rich croc finish.",
    price_pence: 69500,
    image_url: null,
    url: "https://nour-hammour.com/gb-en/products/croco-embossed-leather-day-rouge-croco",
    content_type: "product",
    category: "shopping",
    created_at: "2026-03-20T18:19:31.445Z",
    tags: ["for-her", "luxury", "fashion", "design-led"],
    source_name: "SheerLuxe",
    in_stock: true,
  },
  {
    _key: "mock-002",
    name: "Leather Maxi Skirt",
    brand: "De Savary London",
    description: "A flowing leather skirt with a saturated burgundy tone and dramatic silhouette.",
    price_pence: 42000,
    image_url: null,
    url: "https://www.desavarylondon.com/products/burgundy-leather-maxi-skirt",
    content_type: "product",
    category: "shopping",
    created_at: "2026-03-20T18:18:31.445Z",
    tags: ["fashion", "minimal", "luxury"],
    source_name: "COS",
  },
  {
    _key: "mock-003",
    name: "Burgon & Ball Garden Tool Set",
    brand: "Burgon & Ball",
    description: "Copper-plated hand tools with hardwood handles for serious gardeners.",
    price_pence: 14500,
    image_url: null,
    url: "https://www.burgonandball.com/products/garden-tool-set",
    content_type: "product",
    category: "shopping",
    created_at: "2026-03-20T18:17:31.445Z",
    tags: ["gardening", "home", "premium", "for-parents"],
    source_name: "House & Garden",
    in_stock: true,
  },
  {
    _key: "mock-004",
    name: "Daylesford Herb Growing Kit",
    brand: "Daylesford",
    description: "An elegant indoor herb set that brings kitchen utility and garden charm together.",
    price_pence: 8500,
    image_url: null,
    url: "https://www.daylesford.com/shop/herb-growing-kit",
    content_type: "product",
    category: "shopping",
    created_at: "2026-03-20T18:16:31.445Z",
    tags: ["gardening", "food-drink", "home"],
    source_name: "Country & Town House",
  },
  {
    _key: "mock-005",
    name: "The Dover Terrace Table",
    brand: "The Dover",
    description: "A polished central London dining room with classic service and a clubby feel.",
    price_pence: null,
    price_text: "From £££",
    image_url: null,
    url: "https://thedover.com",
    content_type: "venue",
    category: "going_out",
    created_at: "2026-03-20T18:15:31.445Z",
    location: "Mayfair, London",
    tags: ["restaurants", "date-night", "luxury"],
    source_name: "Time Out",
  },
  {
    _key: "mock-006",
    name: "Riviera Weekend Escape",
    brand: "Maybourne",
    description: "A high-touch Mediterranean itinerary focused on sea views, spa time, and boat days.",
    price_pence: null,
    image_url: null,
    url: "https://www.maybourne.com",
    content_type: "experience",
    category: "travel",
    created_at: "2026-03-20T18:14:31.445Z",
    tags: ["travel", "luxury", "sun"],
    source_name: "Mr & Mrs Smith",
  },
  {
    _key: "mock-007",
    name: "Newt in Somerset Garden Stay",
    brand: "The Newt",
    description: "A countryside hotel with deep horticultural appeal and quietly luxurious rooms.",
    price_pence: 56000,
    image_url: null,
    url: "https://thenewtinsomerset.com",
    content_type: "venue",
    category: "travel",
    created_at: "2026-03-20T18:13:31.445Z",
    location: "Somerset",
    tags: ["gardening", "hotel", "countryside"],
    source_name: "Condé Nast Traveller",
  },
  {
    _key: "mock-008",
    name: "Soho Home Marble Lamp",
    brand: "Soho Home",
    description: "A sculptural table lamp with soft stone texture for warm, collected interiors.",
    price_pence: 29500,
    image_url: null,
    url: "https://www.sohohome.com/products/marble-lamp",
    content_type: "product",
    category: "staying_in",
    created_at: "2026-03-20T18:12:31.445Z",
    tags: ["home", "decor", "design-led"],
    source_name: "Collagerie",
  },
  {
    _key: "mock-009",
    name: "La Fromagerie Cheese Tasting",
    brand: "La Fromagerie",
    description: "Private tasting format that feels thoughtful, social, and lightly educational.",
    price_pence: 12000,
    image_url: null,
    url: "https://www.lafromagerie.co.uk",
    content_type: "experience",
    category: "going_out",
    created_at: "2026-03-20T18:11:31.445Z",
    location: "Marylebone, London",
    tags: ["food-drink", "experience", "giftable"],
    source_name: "SheerLuxe",
  },
  {
    _key: "mock-010",
    name: "Handwoven Cashmere Throw",
    brand: "Brunello Cucinelli",
    description: "An understated luxury piece for homes that lean warm, tactile, and timeless.",
    price_pence: 98000,
    image_url: null,
    url: "https://shop.brunellocucinelli.com",
    content_type: "product",
    category: "staying_in",
    created_at: "2026-03-20T18:10:31.445Z",
    tags: ["home", "for-her", "luxury", "timeless"],
    source_name: "Net-a-Porter",
  },
  {
    _key: "mock-011",
    name: "Lounger Spa Day",
    brand: "Estelle Manor",
    description: "A restorative day built around pools, thermal rooms, and elegant lunch service.",
    price_pence: 32500,
    image_url: null,
    url: "https://estellemanor.com",
    content_type: "experience",
    category: "travel",
    created_at: "2026-03-20T18:09:31.445Z",
    tags: ["spa", "luxury", "giftable"],
    source_name: "CN Traveller",
  },
  {
    _key: "mock-012",
    name: "The Conran Shop Watering Can",
    brand: "The Conran Shop",
    description: "A functional garden object rendered as a design piece for stylish outdoor spaces.",
    price_pence: 9500,
    image_url: null,
    url: "https://www.conranshop.co.uk",
    content_type: "product",
    category: "shopping",
    created_at: "2026-03-20T18:08:31.445Z",
    tags: ["gardening", "home", "design-led"],
    source_name: "House & Garden",
  }
];

export const mockTaskMatch: TaskMatchResponse = {
  intro:
    "Based on gardening and home-focused interests with a mid-range luxury budget, these are the strongest fits from the approved catalogue.",
  suggestions: [
    {
      recommendation_key: "mock-003",
      reason:
        "This feels directly aligned with the gardening brief and lands comfortably inside the stated budget. The finish is premium enough to read as a thoughtful milestone gift rather than a purely practical purchase.",
      match_tags: ["gardening", "premium", "for-parents"],
      confidence: "high",
    },
    {
      recommendation_key: "mock-012",
      reason:
        "A strong option if you want something useful but still design-conscious. It suits someone interested in gardens and home decor without feeling too modern.",
      match_tags: ["gardening", "home", "design-led"],
      confidence: "high",
    },
    {
      recommendation_key: "mock-004",
      reason:
        "This keeps the garden connection but shifts into a softer lifestyle gift, which helps avoid repeating last year's hamper too closely.",
      match_tags: ["gardening", "home", "food-drink"],
      confidence: "medium",
    },
    {
      recommendation_key: "mock-007",
      reason:
        "If the brief can stretch from object to experience, this is highly relevant thematically because the horticultural setting is part of the appeal.",
      match_tags: ["gardening", "hotel", "countryside"],
      confidence: "medium",
    }
  ],
  candidates: mockRecommendations,
};
